### ISSUE TITLE
Unable to play demorecords

### ISSUE THREAD

**Issue by joshuajohnlee** [RadioActivitii/STODemoLauncher#6]
Running the demo launcher seems to list the recordings correctly, but when asking it to play, the EXE is launched and begins loading, but crashes to desktop with the following:

![sto-crash](https://user-images.githubusercontent.com/3915344/229111890-2ce2372a-54da-44bb-93e2-abe39663d414.png)

Checked through log folders and can't see it creating any crash logs unfortunately.

- **OS**: Windows 11
- **STO Launcher version**: CL_2022_01_19_11_11
- **STO Version**: up to date as of 31/03/2023

**Comment by joshuajohnlee** [comment]
I've been trying to get the gameclient.exe to run directly from a command line with the `-demoplay xxxxxx.demo` arguments but it results in the same. Is it possible the exe can no longer be called externally without going through the launcher?

**Comment by radioactivitii** [comment]
Which map is the demo trying to load? Demos still work in the current version of the game, but there's a longstanding issue with demos where some maps can't be loaded and will crash the game instead, which has no fix.

I've also seen an issue where demos stop working but that was fixed by reinstalling the game.

**Comment by joshuajohnlee** [comment]
I couldn't get it to work for any of the demo records I had to test with. Maps tested were

- Tutorial_Starfleet_Academy
- Kfr_Sol_Esd_Ground_02
- Alpha_Quadrant_001_Sector
- Klg_Qonos_Ground_02
- Kfr_Sol_System
- Fed_Player_Starbase_Ground_01
- Starbase_Fleet_Action_01

The only log error I've been able to find (and it may not be related) is:

```
230331 11:51:44    432 Client[0]: GSM_Quit(). Reason: emEditorMain or utilitiesLibShouldQuit()
```

Edit: I'll try reinstalling the game at some point today and see if that fixes anything.

**Comment by joshuajohnlee** [comment]
Reinstall seems to have resolved the issue. Although this time my install is through Steam rather than Arc, but probably was an installation issue on my end then.
